### ISSUE TITLE
Add a few screenshots to the instructions on how to make pull requests from forks

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#11]
Currently, [USAGE.md](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/main/USAGE.md) contains an explanation on how to make pull requests from cloned repositories. 

A similar explanation on how to fetch upstream and how to submit pull requests from forked repositories should be added, as some may prefer to work using this method over cloning.

**Comment by DrMattG** [comment]
We can probably close this now - all the helpful information is linked to in the README and the paper has been resubmitted
