### ISSUE TITLE
Formatting of contributor roles table

### ISSUE THREAD

**Issue by kaitlyngaynor** [SORTEE-Github-Hackathon/manuscript#132]
The contributor roles table is looking great! I think that one way to make it more clear, and to integrate the roles and the features + descriptions, would be to indicate which features will be used by which actors/roles. Not sure exactly what this looks like, but maybe in the style of a feature comparison table where each row is the 'user' and the column is the GitHub 'feature'? not sure how the use cases fit in, though..

from Google, just so you know what I mean:
![image](https://user-images.githubusercontent.com/29489999/157945253-bf1c741c-d3f1-40fd-8823-eb96020e66b4.png)

**Comment by Aariq** [comment]
Hmm, yeah, I think I like it.  So the contributor roles would be rows, github features would be columns (or vice versa), and the cells would contain either simple check marks or potentially shorter descriptions of how the feature would be used.  Like for the intersection of "Reviewer" and "Issues" it could say "suggest changes to code and code artifacts" and for "Co-Author" and "GitHub Pages" it could say "view up-to-date figures, reports, or drafts on the web".  The descriptions of the collaborator roles would then be moved to the table caption, and for the github features we would refer readers to box 1 (definitions).

**Comment by kaitlyngaynor** [comment]
Yeah exactly! I think the descriptions of collaborator roles could actually be the second column instead of the caption: first column role name, second column role description, third+ would be GitHub features. If we can get the descriptions concise, then I think it could make sense to put them in the cells instead of just check marks! concise is key.

**Comment by Aariq** [comment]
Ok, I can take a first crack at making the descriptors more concise (and probably move some info to Box 1 in the process) and draft the new format.  I'll make a PR and we can discuss further there.
