### ISSUE TITLE
Format Box 1 as 1-column table

### ISSUE THREAD

**Issue by Aariq** [SORTEE-Github-Hackathon/manuscript#147]
Can't remember where I saw this suggestion. But it's good

**Comment by emmajhudgins** [comment]
I added it in hypothesis, to which @BrandonEdwards replied. I then suggested @BrandonEdwards follow my formatting used for box 2

**Comment by Aariq** [comment]
Thanks, it looks really good like that.

**Comment by emmajhudgins** [comment]
now resolved in #177
