### ISSUE TITLE
Archive code with DOI

### ISSUE THREAD

**Issue by Aariq** [SORTEE-Github-Hackathon/manuscript#151]
After revisions, remember to set up Zenodo integration and make a release before submission.  Include Zenodo DOI in data availability statement.

**Comment by robcrystalornelas** [comment]
Thanks for this @Aariq. Depending on how funding works out for paper, we will likely have to store/link the dataset in ESS-DIVE instead or in addition to Zenodo.

**Comment by DrMattG** [comment]
Is it okay for me to mark your comment (in relation to this) in the manuscript as resolved @Aariq?

**Comment by Aariq** [comment]
Sure

**Comment by Aariq** [comment]
I think we should keep the issue open until it is resolved here on GitHub though.  We do still need to remember to archive data and code, preferably before pre-print or submission.  A DOI for the repo will be useful to reference in the paper itself (e.g. when we discuss collaborative manuscript writing) as well as in a data availability statement.

**Comment by Aariq** [comment]
Still need to add a DOI badge to the README for the OSF archive and one for the final paper.

**Comment by Aariq** [comment]
Someone pointed out to me that OSF's DOIs are strange and don't actually archive GitHub repos—they just archive a link that points to the live repo.  I know the OSF DOI is already in the paper, but might consider actually archiving this repo with Zenodo anyways??

**Comment by Aariq** [comment]
Another option would be to create a GitHub release, download the zip file of the release, and then manually upload it to the OSF
