### ISSUE TITLE
Style for referencing terms in box 1 within text

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#154]
How do we want to consistently format the key terms we define in box 1 when used throughout the manuscript (if at all?) Do we want to bold, use quotes, italics? Just might be helpful to highlight when these terms are used.

**Comment by Aariq** [comment]
I like bold, but not sure what the journal will want.

**Comment by robcrystalornelas** [comment]
Just checked. Seems like Nature EcoEvo like **bold** for the terms when they first appear in box. No bolding when they are mentioned elsewhere.
