### ISSUE TITLE
Additional table to add to manuscript

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#162]
Hey @Aariq, we do have one more table led by @dylangomes that I forgot to mention. At this point, since it does have some meaningful colors embedded into the table, might just be easiest to insert it as an image, then we can offer feedback via hypothesis. Let me know what you think: https://docs.google.com/presentation/d/1FjRXww7ONYdKvlH3AMW1r2c8CQ0s4PhKaAV4z-BsxPk/edit?usp=sharing

**Comment by Aariq** [comment]
Ah thanks.  I forgot about this one.  Does the data for the table exist somewhere other than this image?  The thing about tables as images is you can't trick Manubot/Pandoc into getting the cross references right.  It seems to treat any image as a figure and I couldn't figure out how to trick it into treating an image as a table.  Might not be a big deal to just do the cross references manually though.

**Comment by robcrystalornelas** [comment]
That's a good question. I think this is the main place that we've all been contributing to the table. I suppose it could be transferred easily to a google sheet instead of a google slide. Not sure if that helps?

**Comment by Aariq** [comment]
I can just turn it into a .csv.
