### ISSUE TITLE
Figure out how to cross-reference arbitrary sections

### ISSUE THREAD

**Issue by Aariq** [SORTEE-Github-Hackathon/manuscript#169]
In order to reference Box 1 (definitions of GitHub terms) and Box 2 (tips on getting started) we could try to figure out how to do that with cross references (`@box:definitions` doesn't seem to point to a H3 with `{#box:definitions}` like I thought it might).  Possibly not worth it as there are only 2 boxes and order is unlikely to change---manual references will work fine.

**Comment by Aariq** [comment]
I think this pattern should work:


```
Just push changes (see [Box 1](#definitions)).

### Box 1 {#definitions}
branch: ....

```

**Comment by robcrystalornelas** [comment]
@Aariq Just want to confirm, based on this link: https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html#box:box-1-definitions

Would the correct way to link to box be ([Box 1](#box:box-1-definitions))

**Comment by Aariq** [comment]
> 



> @Aariq Just want to confirm, based on this link: https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html#box:box-1-definitions
> 
> Would the correct way to link to box be (Box 1)

If you want the rendered text to look like "Issues can be used to divide up tasks ([Box1]( https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html#box:box-1-definitions))."  Then the markdown you'd write is:

```
Issues can be used to divide up tasks ([Box1](#box:box-1-definitions)).
```

But I'd suggest editing the id of Box 1 to just be `{#definitions}` to make it easier to reference.
