### ISSUE TITLE
cover letter submission - a couple of comments

### ISSUE THREAD

**Issue by DrMattG** [SORTEE-Github-Hackathon/manuscript#173]
@robcrystalornelas @pedrohbraga - I am not sure if this is the best place for discussing the cover letter - but I have some thoughts...(some of which are pedantic and none of which are "hills I will die on")

[This line](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/8c6c9aa0e662161c4b8070d081d57ca7d5b6e97e/editorial-communication/cover-letter-submission.Rmd#L19) seems a little orphaned and I think the following [paragraph](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/8c6c9aa0e662161c4b8070d081d57ca7d5b6e97e/editorial-communication/cover-letter-submission.Rmd#L21), which speaks to the potential auidence for this paper is more valuable coming straight after the openning "gambit".  

The term ["self-teach"](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/8c6c9aa0e662161c4b8070d081d57ca7d5b6e97e/editorial-communication/cover-letter-submission.Rmd#L23) jars my English sensabilities. I might extend this sentence to something like:  "Albeit, many researchers lack exposure to adequate software development practices and thus are required to dedicate valuable time and effort to learning how to use research-facilitating tools. Formal academic courses on these types of tools in Ecology and Evolution are often unavailable and researchers are left to learn through informal blogs, videos and other online forums. This may present a plethora of practical barriers to applying adequate standards to maintaining scientific code"... or something like that!

[This line ](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/8c6c9aa0e662161c4b8070d081d57ca7d5b6e97e/editorial-communication/cover-letter-submission.Rmd#L27) might benefit from an extra clause - "Our manuscript is the most accessible and practical guide to using GitHub in E&E research to date. We build upon some existing resources, which are mainly targeted at other disciplines, and our own experiences (from across all the subdisciplines of E&E) in writing and sharing code openly, to highlight steps E&E researchers can take to improve their research practices in an reproducible, collaborative and transparent way." This [line](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/8c6c9aa0e662161c4b8070d081d57ca7d5b6e97e/editorial-communication/cover-letter-submission.Rmd#L28) would need to be deleted. 

I noticed this in the main MS too we have used two acronyms for the same thing (I assume its the same!) (https://github.com/SORTEE-Github-Hackathon/manuscript/blob/8c6c9aa0e662161c4b8070d081d57ca7d5b6e97e/editorial-communication/cover-letter-submission.Rmd#L29) - EEB and E&E

Should we state [here](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/8c6c9aa0e662161c4b8070d081d57ca7d5b6e97e/editorial-communication/cover-letter-submission.Rmd#L31) that we are going to preprint this manuscript (if we are that is). NEE are supportive of preprints.

Matt

**Comment by robcrystalornelas** [comment]
@DrMattG All really good points, and thanks for all the links so we know exactly what parts of the letter you are talking about.

I'll work on a PR today with the items that can be added/modified directly in the cover letter. (e.g., I agree we should just change language to always reference EEB since it appears throughout the manuscript).

I think pre-printing is a great idea.  I'll open up a discussion thread about that since I think that's a better forum for getting group input on where we should pre-print.
