### ISSUE TITLE
Figure 2 has a few artifacts and could be improved for resolution and colour contrast with the background

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#198]
Hi,

Figure 2 looks very awesome (!!!). However, I have found a few issues with it, which I list below:

1. When contrasted with darker colours, it shows x-axis and y-axis tick numbers (ranging from 0 to 5 and 0 to 15, respectively) in white colour (see below);
2. When contrasted with darker colours, the extreme categories or labels (the muted red at the top and the purple and blue at the bottom) are difficult to read. When contrasted with bright colours, the categories in the middle become difficult to read;
3. Image resolution is currently set to 96 dpi (however, I am not certain if this is Manubot that is converting it to a lower resolution (I will confirm); 
4. A few minor typos (for the sake of consistency) in the x-axis tick labels and categories, so they match the rest of the figure: "Working diaries/blogs", "Upper-Intermediate", "Pre-Intermediate", "Low-Intermediate", and "Hosting and deploying academic websites";
5. Finally, I think that we perhaps want to be more specific with respect to "the community" and "the public". We use both "user-community" and "EEB community" in the text, and it is not clear which one we are referring to. It also would be good to do the same for "the public", as it is not clear to the reader whether we are speaking of "non-academic GitHub users" or the "general public".

I think that a quick fix for issues (1) and the first half of issue (2) could be to force a white background on the figure so that we ensure that readers are always looking at it in our desired background colour. 

Nevertheless, the issue with the colours in the middle might still be prevalent after this adjustment. These colours can be muted to improve their contrast, or alternatively, we could use other colour gradients (_e.g._ something like the [`Zissou1`](https://github.com/karthik/wesanderson#the-life-aquatic-with-steve-zissou-2004) from the `wesanderson` R package or a sequential palette from the `RColorBrewer` R package) to describe the technical difficulties in the tasks using GitHub.

We may also be required to increase figure resolution to match journal requirements (>= 300 dpi).

Let me know if you need to discuss further some of these suggestions I raised!

Thank you again for having worked to create this figure! I find it came out great!

**Comment by pedrohbraga** [comment]
I have forgotten to add screenshots of the figures with different backgrounds. Here are the examples as they appear to me:

1. Directly from Manubot:
![image](https://user-images.githubusercontent.com/8599229/168964615-54c00e8d-bab9-4a6e-9161-0ce674e71829.png)

2. When opened in a new tab:
![image](https://user-images.githubusercontent.com/8599229/168964711-79a37a71-8b58-433b-90ce-fe8f0a6bd22c.png)

3. When shown in GitHub:
![image](https://user-images.githubusercontent.com/8599229/168964844-aee63353-df78-4572-8ae2-d2cea1562102.png)

**Comment by robcrystalornelas** [comment]
Thanks for the comments @pedrohbraga. I'm going to add @LunaSare here for when we make the next round of edits. Also this issue is linked to another issue by @Aariq in issue #160

**Comment by LunaSare** [comment]
Thanks for tagging me @robcrystalornelas. These are good comments @pedrohbraga! 

I can work on it and have it updated soon, probably by Friday!

**Comment by robcrystalornelas** [comment]
Thanks @LunaSare one more thing to note. In this last round of edits we removed the "miscellaneous"section about different ways to use GitHub. So it will likely be best if the number of blobs aligns with the total number of ways to use GitHub.

**Comment by LunaSare** [comment]
Addressing Pedro's and Rob's comments!

> 1. When contrasted with darker colours, it shows x-axis and y-axis tick numbers (ranging from 0 to 5 and 0 to 15, respectively) in white colour (see below);
- [ ] Force background to white on all figures
> 2. When contrasted with darker colours, the extreme categories or labels (the muted red at the top and the purple and blue at the bottom) are difficult to read. When contrasted with bright colours, the categories in the middle become difficult to read;
- [ ] Try color schemes from `wesanderson` package, and
- [ ] other color schemes from virids
> 3. Image resolution is currently set to 96 dpi (however, I am not certain if this is Manubot that is converting it to a lower resolution (I will confirm);
- [ ] Increase resolution
> 4. A few minor typos (for the sake of consistency) in the x-axis tick labels and categories, so they match the rest of the figure: "Working diaries/blogs", "Upper-Intermediate", "Pre-Intermediate", "Low-Intermediate", and "Hosting and deploying academic websites";
- [ ] Fix
> 5. Finally, I think that we perhaps want to be more specific with respect to "the community" and "the public". We use both "user-community" and "EEB community" in the text, and it is not clear which one we are referring to. It also would be good to do the same for "the public", as it is not clear to the reader whether we are speaking of "non-academic GitHub users" or the "general public".
- [ ] Homogenize to EEB community for community and user-commuity to the public (?) Might use some input from @robcrystalornelas and maybe @kaitlyngaynor and @emmajhudgins here
> ... removed the "miscellaneous"section about different ways to use GitHub. So it will likely be best if the number of blobs aligns with the total number of ways to use GitHub.
- [ ] remove miscellaneous uses from table and check that we have 12 uses only in figures

**Comment by emmajhudgins** [comment]
awesome work Luna! I agree with other that viridis turbo looks best!

**Comment by kaitlyngaynor** [comment]
All great! minor comment as I look at this anew, would "Degree of collaboration" rather than "Degree of collaborativeness" be better? I'm not sure collaborativeness is a real word hah

**Comment by robcrystalornelas** [comment]
Agreed Kaitlyn, we were discussing this in the comments on Pull Request #212, I think Luna will change this wording.
