### ISSUE TITLE
Author contributions statment using CRediT

### ISSUE THREAD

**Issue by Aariq** [SORTEE-Github-Hackathon/manuscript#199]
The latest email about author order reminded me that it might be a good idea to include an author contributions statement in the manuscript.  Making this statement could also help us feel more confident about author order.  

The Contributor Roles Taxonomy is one possible guide for structuring such a statement:
https://credit.niso.org/

**Comment by robcrystalornelas** [comment]
I figured the discussion section might be a good place to start drafting the statement. What do you think about #200
