### ISSUE TITLE
GitLab

### ISSUE THREAD

**Issue by Aariq** [SORTEE-Github-Hackathon/manuscript#208]
Just realized we have not mentioned GitLab, but I think it might be worth a phrase or a sentence in the intro.  The major difference (I think) is that GitLab can be self-hosted (https://about.gitlab.com/install/).  That means you could run it on a University or lab server, for example.  I get the sense (from asking the US-RSE Slack) that some academics/govt labs prefer it because they have more control.

**Comment by Aariq** [comment]
Oh, nevermind, I do see that it is mentioned in  "Why aren't more EEB researchers using GitHub?" parenthetically.  Perhaps that is enough.

**Comment by robcrystalornelas** [comment]
Yes, I think that's enough in terms of going into GitLab.
