### ISSUE TITLE
Change mention of "software" to "code"

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#215]
@Aariq mention in hypothesis that we might, in the intro of our paper include a statement like: "software packages or data analysis code (hereafter, code)". This way we only need to refer to 'code' throughout the rest of the paper.

I agree with this change, and have created this issue since we'll need a PR to make this change throughout the manuscript

**Comment by DrMattG** [comment]
Makes sense to me

**Comment by fhillemann** [comment]
agreed, makes sense. I've changed this to "code" in the discussion.
