### ISSUE TITLE
Convert "repo" to "repositories" in manuscript

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#216]
@fhillemann brought up question of whether we want to use "repo" in manuscript, or just "repository" throughout. What do you all think? If so, we'll use this issue since a PR will need to address each file of the manuscript.

**Comment by DrMattG** [comment]
I think "repos" is okay as long as we say something first like "repositories (often referred to as repos)..."

**Comment by emmajhudgins** [comment]
i can see using repo to get the reader comfortable with github lingo, but also note it doesnt shorten our word count and repository is more clear

**Comment by Aariq** [comment]
I thought I got them all.  I did a find and replace on the whole repo.

**Comment by robcrystalornelas** [comment]
I thought I saw one last repo in a table. I'll double check and will submit a PR if I find it.

**Comment by robcrystalornelas** [comment]
There were another couple of "repo" in the tables. Fixed in #218
