### ISSUE TITLE
Update needed to figure 1

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#230]
The thin dotted lines going from panels back to original are too small. I can barely see where they are going and I've got good eyes. I would either make them more noticeable, or remove completely.

Should the letter "B)" be located down at the bottom left corner of the plot? I am not understanding what it is supposed to be referencing. I would think it would be near the panel at the top that lists "issues, pull requests, discussions," etc.??

I like this figure! I might recommend re-ordering the contributors in panel D so they are in the same order as the files in the left column. Then the arrows won't cross and it will be a lot easier to follow them.

Where the caption says "CONTRIBUTING.md, LICENCE.md, & README.md files" All of these things are actually listed by "B)" in the figure, not D)

**Comment by colebrookson** [comment]
These are great comments, thanks Rob! Fixed! 
![fig-1-edited](https://user-images.githubusercontent.com/43683737/173260633-d2d5b60f-92c3-4a5d-9f05-cb9906090c00.png)
