### ISSUE TITLE
GitHub icon broken on manuscript page

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#235]
Small issue @pedrohbraga but looks like the github icon isn't loading in our authors list:

![image](https://user-images.githubusercontent.com/15171529/173391094-6e6d5ee6-374a-4a95-98a5-180e42c9f439.png)

**Comment by DrMattG** [comment]
It was removed by this PR https://github.com/SORTEE-Github-Hackathon/manuscript/commit/a98fb6a67e53a1f0e5b1e8eacf901515fad3e8cc - if that helps
