### ISSUE TITLE
Updating figure 1 legend

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#236]
Looks like the figure 1 legend needs to be updated to account for the changes to figure. E.g., there is no section D now

I'm happy to try and work on this or if you have a chance, go for it @colebrookson

**Comment by colebrookson** [comment]
Whoops, my bad, on it!!

**Comment by colebrookson** [comment]
@robcrystalornelas can you remind me where in the repo we're keeping the figure captions?

**Comment by robcrystalornelas** [comment]
@colebrookson it's in this file. https://github.com/SORTEE-Github-Hackathon/manuscript/blob/main/content/09.figures-tables.md

You'll need to go into edit the markdown file to actually see the caption though since the caption doesn't render in the github UI

**Comment by colebrookson** [comment]
Ahhh got it. I didn't realize it didn't render in the UI, thank you! Done!
