### ISSUE TITLE
Updating table order

### ISSUE THREAD

**Issue by robcrystalornelas** [SORTEE-Github-Hackathon/manuscript#252]
Hi @Aariq, hoping you might be able to help with re-ordering tables. 

Essentially, we need the manuscript updated so that:

**Table 1** is the comparison table
**Table 2** is the Roles table

in PR #251 I managed to make sure the actual text in the manuscript is corrected so that Table 1 is comparison table and table 2 is the roles table. I think their links will work as well.

_However,_ even once that PR is merged, I think the roles table will appear first **when it should now appear 2nd** AND the **table captions might still be mis-labeled with their numbers reversed**.

Hopefully once the PR is merged this will be a quick fix. Think you will be able to make adjustments? Thanks!

**Comment by Aariq** [comment]
Sorry I missed this.  Did the table refs end up working or is this still open?

**Comment by robcrystalornelas** [comment]
No worries @Aariq I could still use help with this. My last PR didn't quite resolve the issue.

Any chance you are able to work on this?  In addition to swapping the actual order of table 1 and table 2, could you also double check that the links are going to the right place in the manuscript? I can double check that as well.

**Comment by Aariq** [comment]
I can take a look later this week I think

**Comment by robcrystalornelas** [comment]
I was able to fix table order so will close this issue
