### ISSUE TITLE
Concern: Perception of insufficient contextualized usage of GitHub specific to researchers in ecology and evolution

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#260]
Hi, everyone

I hope you are all well! 

I have a few concerns and comments related to our manuscript that I would like to raise as issues, so that we can discuss them and, if necessary, address them prior to the submission of our manuscript for consideration for publication in a peer-reviewed journal.

**Concern**

In this issue, I would like to comment on the apparent lack of domain-specific contextualized usage of GitHub in the manuscript.

While we frequently use the term “ecology and evolutionary biology” (EEB) to help cater our manuscript to our choice of public, most of the applications that we explicitly provide are non-EEB specific.

There are a few examples in the use cases [_e.g._, the R packages in the “Peer review” section, and some places where we discuss laboratories (but note that there are laboratories in non-EEB fields)].

It is great (and natural) that we have content that can be used by researchers in other domains. However, I feel that more domain-specific applications of the usage of GitHub can help our readers and researchers in ecology and evolution reflect better on how they can use GitHub in their hands-on research projects. Ultimately, the journals we are aiming at are specific to ecology and evolution, and I fear that reviewers and editors might express concerns about this in the initial parts of the review process.

I acknowledge our challenges in trying to contextualize this super broad tool to EEB researchers, as well as our limitations with the text length. Some of the applications we discuss would not require this type of specificity (_e.g._, manuscript writing).

**Proposed solution**

A potential solution that I see to adjust for this perception is to include more field-specific applications for GitHub across the text, such as examples of usage with long-term ecological studies, sequencing and assembly of genetic databases, simulations of communities or metacommunities and their applications in theoretical and empirical studies.

For example, the automated near-term iterative forecasting systems that have been developed for the long-term ecological study in Portal (Arizona, US; https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13104). Another example could be the reproducible pipeline for the study by Kazelles _et al_. (2019, Global Change Biology; https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.14829), which has an automated pipeline and a binder associated (https://github.com/McCannLab/HomogenFishOntario) with the GitHub repository that automatically runs and reproduces the analyses and figures that are published in their study. 

Please let me know what you think about this concern, if you have a proposition, and (if needed) if you could help with some of the additions to the manuscript.

**Comment by dylangomes** [comment]
I am wondering if the easier solution is to broaden the scope of the title and journal submission? Keeping the article broader will probably have a larger impact as well. Thoughts?

**Comment by robcrystalornelas** [comment]
@dylangomes That could work, you are thinking we try for a different/more general journal?

**Comment by dylangomes** [comment]
It's just an idea that I am certainly not wedded to, but it seems to have several advantages 1) not needing to rework the manuscript to include specific E&E examples, 2) being useful to folks across disciplines by keeping it general, and 3) saving the trimming work to get the word count down.
PLoS One is a possible general outlet (example: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0229003).

**Comment by robcrystalornelas** [comment]
Makes sense to me! Thanks for elaborating on that. What do you think @pedrohbraga?

**Comment by dylangomes** [comment]
I am sure there are lots of other general outlets, I just included one that immediately came to mind. Happy with whatever y'all decide 👍

**Comment by DrMattG** [comment]
My view is that if we can painlessly incorporate examples from Ecology and Evo uses then great - if not then I dont see it as a huge issue - we are talking about the potential for using GitHub for EcoEvo folk. 

I would also not be opposed to @dylangomes's suggestion

**Comment by colebrookson** [comment]
I agree that @dylangomes 's suggestion is a good one worth considering and would definitely be the least work. However, my concern would be that I think other fields of science/biology are a bit further down the version-control usage pipeline than EEB (not always but definitely sometimes), so I worry the content we provide here, which I perceive to be more of trying to convince EEB-ers to use this or some other equivalent resource, might not provide as novel use cases to other disciplines. I.e. I have seen many papers of this nature but possibly for the more advanced user published in PLoS Comp. Biol. or related, and I would worry that there wouldn't be enough "new" content presented here to appeal to a journal like that. Thoughts?

**Comment by pedrohbraga** [comment]
I understand the recommendation to broaden our scope and readership toward non-EEB scientists. However, I feel that this departs from our initial aim to provide a practical guide for EEB researchers and that it could put our use cases and our perspectives a bit more disjoint with the usage of GitHub in other fields. I feel that I am more limited in the extent of the recommendations I can make to these other fields.  I concur with @colebrookson on these points. 

I also feel that the edits required to convert the text toward a non-EEB could potentially be very extensive, as we have many arguments catering GitHub to EEB scientists and recalling that the absence of a field-specific guide is needed to encourage EEB researchers to use GitHub more in their research.

Just to clarify my concern: my thought was that the text could benefit from a few more specific applications through a few citations or a few short examples.

**Comment by robcrystalornelas** [comment]
Good points everyone! Such good discussion here--I appreciate everyone's input.  I'll give another few days for people to provide additional thoughts.

Right now, I'm leaning toward the following steps:

1. See if anyone **volunteers and/or submits PRs** to add more EEB-specific language and citations to the use cases.
2. Either way, submit to _Nature E&E_ and see what decision they make
3. If we get a reject, try another journal. To @dylangomes's point, I agree that PLoS one would be a good fit. Though the journal is geared toward a general audience, they publish ecology-specific articles all the time, so I don't think we'd have to edits the EEB references out.

**Comment by robcrystalornelas** [comment]
@Aariq I'm going through a bit now and seeing what I can add for EEB-specific citations.  But if either you or @pedrohbraga would like to add in some field-specific use cases and submit a PR, that'd be helpful--thank you!

**Comment by robcrystalornelas** [comment]
Thanks @katherinehebert 🙌🏻 I'm doing a final read through now and will incorporate this citation.
