### ISSUE TITLE
Minor Concerns: Citations needed across the Discussion and Text length must be shortened

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#262]
Hi. Below, I list a few minor and specific concerns in relation to the manuscript:

- [ ] 1.  **Certain sentences from the Discussion seem to need some citations to support them.** Examples are "First, there may be hesitation to independently adopting and learning a new tool. Institutional encouragement and instructional resources focused on researchers in ecology and evolution may be limited." and "We suspect a major additional barrier to EEB researchers is a distinct lack of GitHub help documents for non-English researchers in ecology and evolution, meaning that EEB researchers potentially miss the opportunity to fully understand the importance of version control, reproducibility, and other benefits of GitHub." 

- [ ] 2. **Text length needs to be reduced.** Journal guidelines establish that the manuscript must be 4000 words. Right now, we are a little above 4600 words. A few examples and sections can be shortened to allow us to get closer to the journal's word-limit requirements.

- [x] 3. **The use case "GitHub Organizations" appears disjoint from the other titles. Would it be adequate to use "Institutional organization"?**

**Comment by dylangomes** [comment]
RE #2, are you sure that this is a strict guideline? In my experience journals almost never care about a few hundred words over during the submission stage and also don't seem to mind during the publication stage either (although sometimes they have page charges). My suggestion would be to not worry about 600 words over the limit (unless the guidelines sound very strict around this).

**Comment by robcrystalornelas** [comment]
I agree with you @dylangomes, fixing the word count is very low priority to me.  Whenever this goes out to review we'll inevitably get comments that modify word length. This will get figured out in later versions of the MS.

**Comment by DrMattG** [comment]
On #2, I agree with @dylangomes & @robcrystalornelas. 
On #3, as GitHub organisations is not a "product" (or service) I would say that it should be written "GitHub organisations" throughout (as opposed to say "GitHub Actions").
On #1, (sorry for the weird ordering!) I suspect we might struggle to find references that actually reflect these sentiments and we do not want to be "forced" (not the right word but it is holiday time and my brain is fried!) in to poor citation practices. If we can find some references for these statements then great - if reviewers/editors agree with this issue then we can find ways of rewording these sentences to reflect that they are our (collective) opinion.

**Comment by robcrystalornelas** [comment]
Hope you are having a good vacation @DrMattG!! 

I addressed point 2, but to your point 1 and 3 @pedrohbraga:

1) As Matt said, some of these sentences just don't have existing research to cite. But, we use language like "We **suspect** a major additional". This type of phrasing should indicate to the reader that it's simply our intuition.  I would also wait for reviewers to identify if this is a problem or not rather than deeply searching for references which probably don't exist.

3) I think we should just keep GitHub Organizations

**Comment by pedrohbraga** [comment]
Hi, all! 

Thanks for the feedback here! I understand that there is not a big issue with the word limit and I also understand your point about citations! 

The only one that was not clear to me was the last one. I will clarify what I mentioned earlier:

GitHub Organizations is a feature from GitHub (https://support.github.com/features/organizations), like Actions, Issues, and Discussions. 

In all use cases, we are guiding researchers on how to use features from GitHub to "store and share research compendia", "manage projects", and "host a website", which I feel makes it disjoint from the rest of the use cases to dedicate a title to a feature ("GitHub organize" (?)).

In this section, we are recommending users manage teams and create repositories that are linked to an institution or to a laboratory using GitHub, its repositories and the Organizations feature.

Let me know what you think!

**Comment by dylangomes** [comment]
@pedrohbraga just to clarify, you are suggesting that devoting a section title to a github capability name (e.g. GitHub Organizations) rather than to what it does (e.g. organize groups) doesn't mesh with the other section titles? What you are saying makes sense to me - if I am interpreting you correctly. 

Some possibilities might be: organize your working group, organize and manage your team, collaborate in a centralized laboratory space ... or some combination of these?

**Comment by pedrohbraga** [comment]
> @pedrohbraga just to clarify, you are suggesting that devoting a section title to a github capability name (e.g. GitHub Organizations) rather than to what it does (e.g. organize groups) doesn't mesh with the other section titles? What you are saying makes sense to me - if I am interpreting you correctly.

Yes! This is what I wanted to express!

I like your suggestions for "Organizing and managing teams" or "Organizing and managing working groups"!

**Comment by robcrystalornelas** [comment]
I like 'Organizing and managing teams' it's just a bit more concise and still leave it open as to what we mean by teams. I think that could work well!

**Comment by pedrohbraga** [comment]
Hi! I am closing this issue, as the other two topics were minor and seem to be not essential to continue with the submission. Thank you all once again!
