### ISSUE TITLE
R1.1: Request to shorten and reduce the repetition and complexity of certain parts

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#277]
Reviewer's 1 comment:

> R1.1. This paper clearly communicates the enthusiasm of the authors for integrating GitHub in the EEB research process. Advantages in areas of collaboration, transparent and reproducible science are clear and nicely discussed. This is a well written paper. I would, however, recommend some restructuring and shortening. As it stands, this paper is too long and some of the use cases are too nerdy to spark enthusiasm in somebody who is not already using GitHub. Breaking it into 13 use cases leads to some repetition and those use cases may be combined more effectively for convincing a new user.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by Aariq** [comment]
To do:
- [ ] Thorough read-through to determine if any sections can be merged
- [ ] More cross-referencing among sections to reduce repetition
- [ ] Identify the most "nerdy" use cases
- [ ] Edit "nerdy" sections:
      1) make shorter and less detailed
      2) re-frame in less nerdy terms
      3) re-frame as extensions to other use cases (e.g. once you master xyz, you can do <insert "nerdy" thing> to make it even better)

**Comment by Aariq** [comment]
IMO the current Virtual laboratory notebooks sections is about two things: 1) a lab notebook kept by a researcher as a log of experiments, analysis, etc, but stored electronically. 2) An editable book/wiki of Lab (as in 'the Scott Lab') procedures, policies, and protocols. I think it could be split and merged with other sections.

Sections that could be merged:
- Storing & Sharing research compendia + first part of virtual laboratory notebooks -> Project continuity
- Educational Materials + Hosting a website + 2nd part of Virtual laboratory notebooks = Hosting a personal, lab, or course website

**Comment by Aariq** [comment]
I got rid of the virtual lab notebook section (and moved the contents to other sections) in PR #303 .  Would love to get your feedback on it @emmajhudgins.
