### ISSUE TITLE
R1.2: Request to focus on tailoring the language and use cases to entry-level researchers

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#278]
Reviewer's 1 comment:

> R1.2. The title and abstract gave me the impression that the goal is to convince EEB researcher to start using GitHub. If that’s the case, it might be better to tailor the use cases to that entry level and use less GitHub specific lingo. Advanced usage may be mentioned but not detailed as much as it is currently done. E.g. collaboratively writing a paper in GitHub is probably out of the question for most. Most GitHub options for communication, discussion, issue tracking are still somewhat esoteric for most non-programmers.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by robcrystalornelas** [comment]
@Aariq do you feel like this issue is taken care of with changes we are making in #277

**Comment by Aariq** [comment]
It's definitely related.  Still working on converting some barrier-like language (e.g. "more difficult", "challenging") to friendlier and more informative language reflecting that some GitHub uses require more time (e.g. "more advanced", "greater time investment") in #297
