### ISSUE TITLE
R1.3: Request to define the attributes of GitHub in terms of investment return on time and effort

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#279]
Reviewer's 1 comment:

> R1.3: Although the abstract states ‘We outline features ranging from low to high technical difficulty’ the paper reads a bit like a laundry list of what GitHub can do (in fact, the word ‘can’ is used about 140 times, which makes for tedious read). Figure 2 helps sort through this laundry list and defines the technical difficulty. It might be better to clearly lay out where anybody can start using GitHub effectively in the text. And the emphasis is on ‘effectively’. Most people are not likely to learn a new piece of software if it does not promise to reduce effort and time. So, defining tasks where GitHub shines in terms of return on investment maybe the better approach to convincing new users and then only mention the advance use cases with some pointers to further reading, but not going into too much detail.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#`) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by Aariq** [comment]
Related to #277—I suspect the reviewer considers a use case more "nerdy" if the return on investment is not as good for a typical EEB researcher who doesn't know GitHub already

**Comment by Aariq** [comment]
Difficulty is less subjective, but return on investment is pretty subjective and depends on the researcher/lab.  Might want to push back on this one.  We can implement specific suggestions on section order in #280

**Comment by robcrystalornelas** [comment]
Yes, I think we push back here, and do not try to predict ROI since that will vary depending on the researchers/lab/project.  In our response point to acknowledgement that we call out not all items in our list will be useful for everyone since as we say:

> On the other hand, some examples we described here, including course material development, web hosting, and automation, require greater effort and time commitment, but have the potential to make EEB research more open, accessible, and collaborative.

Additionally, figure 2 effectively quantifies as general version of ROI as I feel comfortable outlining.  Pick the lowest items on the difficulty scale that span many degrees of collaboration (e.g., archive your code to make it citable, store your research items, start w/ project management).

**Comment by pedrohbraga** [comment]
I appreciate the reviewer's suggestion. A return-of-investment index is attractive, but its estimation requires a dedicated study. I am closing this issue because it has been addressed within the response letter. Thank you all for your input.
