### ISSUE TITLE
R2.1: Improvements to legibility and abstraction on Figure 1

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#282]
Reviewer 2 comments:

> The manuscript presents how ecologists and evolutionary biologists (EEB) can use collaborative software development project management tools. The authors present a high-level view of Github and the Git version control system that is at its core. As the authors detail, the tools that Github provides has broad potential to be leveraged within the EEB community. The paper is well written and helps to make Github tools and related concepts legible to EEB audiences. On the whole, I see this as potentially being an impactful paper for improving EEB research. I have the following Major and Minor comments for the authors:
>
> Major Comments
>
> R2.1. Figure 1 was more confusing to me than helpful. It presents a view of a Github interface in order to detail generalized features; however, it is edited/abstracted so much that it doesn’t map easily to the interface as it would be viewed by a reader of the paper. To improve this I would reduce the level of abstraction of the web interface.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by robcrystalornelas** [comment]
@colebrookson might you be able to make these changes?

One quick fix could be to completely remove the "zoom in" portions of the diagrams and just put the A, B, C labels next to the actual parts of the abstracted GitHub UI?

If you do that than the single image of the whole repository can be larger and fonts will be legible.

**Comment by emmajhudgins** [comment]
@robcrystalornelas I believe @fhillemann was taking this on following our meeting in dec with @Aariq @pedrohbraga @LunaSare

**Comment by fhillemann** [comment]
How about this? Let me know if I should blur more parts of the screenshot, or/and overwrite commit messages with a descriptive text, e.g. "latest commit messages associated with the file", or if you would like to suggest other changes.

Figure caption: 
Edited screenshot of the GitHub User Interface for the repository associated with this manuscript, showing Git’s core features. A) Issues, Pull Requests, Discussions, and Projects allow for team members to ask for feedback, suggest fixes, discuss related ideas, and keep track of all the moving parts of a project. B) Multi-faceted components allow for code writing, small data storage, manuscript writing, and project management to all be done in one place. CONTRIBUTING.md, LICENCE.md, and README.md files allow new team members, or others wanting to use materials, to understand the project components and learn how they can engage with the project and existing team members. All files within the repository are shown with their most recent commit message and time of the last commit. C) Collaborators on a project can be a part of a single repository, with varying push privileges and responsibilities.

![Figure1](https://user-images.githubusercontent.com/67734235/212509527-7275154f-093e-41f0-b30c-2d364b962704.png)

**Comment by pedrohbraga** [comment]
Hi, @fhillemann! This is awesome! It is much clearer, and the figure has already been incorporated into the manuscript.

A little request on this: 

1. Which software have you used to create the PDF and PNG files you made the pull request for?
2. If you used something like Photoshop, would you be able to add the editable file to the repository, so we can go back to it later on? It is likely that the journal will require us to re-export it with more dpi, as it currently has 92 dpi and Wiley requires 300+ dpi.

I will close this issue as soon as you OK this message, as it has been solved in #306 , #236 , and #230

**Comment by fhillemann** [comment]
Awesome, thanks @pedrohbraga, yes the issue can be closed.
To answer your questions: 
1. I raggedly used Keynote on my Mac.. but just created a version in GIMP (free cross-platform image editor)
2. Yes, will add the GIMP .xcf file and higher resolution files now

**Comment by fhillemann** [comment]
...turns out I can't upload a .xcf GIMP file

**Comment by pedrohbraga** [comment]
Understood! 

@fhillemannm, do you know what is preventing you from uploading the XCF file? 

This repository has a file with that extension: https://github.com/FHPythonUtils/LayeredImage/tree/master/tests/data.

Would it be a file size issue?

If you are unable to upload it, could you please send it to my email? I will add it to the files for the manuscript and find an alternative to keep a version on the cloud.

**Comment by fhillemann** [comment]
not sure why I initially couldn't upload the GIMP .xcf file, but it worked now. 
higher-resolution .png and .xcf for Figure 1 uploaded to \content\images
