### ISSUE TITLE
R.2.2: Clarify how technical difficulty in Figure 2 was assessed

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#283]
Reviewer 2 comments

> R2.2.  Figure 2 was useful, especially as it summarized across multiple areas that a reader make in-roads into using Github. Please clarify how the “Technical Difficulty” was assessed. Was this based on the impression of the working group? Was it quantified using different types of required knowledge (e.g., programming, software design, working in the Terminal, etc.)?

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by emmajhudgins** [comment]
@LunaSare made a spreadsheet from which this was calculated, which was created/discussed with @robcrystalornelas and myself

**Comment by pedrohbraga** [comment]
Perhaps a potential solution here could be to summarise the content of `R/scatterblob.Rmd` (or `R/scatterblob.pdf`) in the form of an Appendix, export it as a Supplementary Material, and refer to it in both the legend and first citation for Figure 2.

**Comment by LunaSare** [comment]
I like the idea of adding the data as an Appendix! Although, I thought mentioning that the data was available from the repo would be enough, but maybe it was not clear enough for the reader. I'll work on this and report back :shipit:

**Comment by pedrohbraga** [comment]
Yes, @LunaSare! We can add a table with the categories and their values to the Supplementary Material (as Table S1, for example), but an Appendix (such as Appendix S1) detailing the criteria for each decision and that these resulting values were plotted to create Figure 2 would satisfy the reviewer! 

Let me know if you need help!

**Comment by LunaSare** [comment]
Awesome @pedrohbraga ! 

So, the [scatterbolb.pdf](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/main/R/scatterblob.pdf)is already formatted as supplementary material, but it does not display the raw data, it is just the code to create the figure with R.

I could add a table with the data to that Rmd and pdf, or create an independent Rmd and pdf file for just the data table, so that the data is easier to find. What do you think?

Also, to add a Supplementary Data or Appendix section, do we add this as an md file to the content folder? I'll probably need help with the manubot part of this 😅

**Comment by pedrohbraga** [comment]
Hi, @LunaSare. I created #298 to show more or less what I was thinking about.

You can regenerate that `.Rmd` file on your end, and once it is ready, we can just add the `.pdf` as supplementary information without needing to work with Manubot.

Regarding your last question, I think that the table can be useful. I have seen that you load it with RMarkdown, so you can probably use `kable` to directly represent it in the RMarkdown document as Table S1.1.

Let me know if you need help!
