### ISSUE TITLE
R2.5: Replace Figure 1 or add another figure detailing generalized research workflow contextualized with the use cases

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#286]
Reviewer 2 comment

> R2.5. Related to Major Comments 1 and 4, given that the focus of the paper is toward integration into EEB scientific research workflows, I suggest adding another figure (or replacing Figure 1) that details a generalized scientific research workflow (e.g., Munafò et al. 2017 https://www.nature.com/articles/s41562-016-0021) and how Github supports/augments that workflow. This could relate to or build on Table 2, which a useful summarization of important features as they relate to different research participants.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by emmajhudgins** [comment]
this seems like the trickiest one and the one we might need the most (sub)group discussion on

**Comment by Aariq** [comment]
In an ideal open science world, the entire scientific workflow is on GitHub.  Plus we outline uses outside of scientific workflow, per se, like professional development.
