### ISSUE TITLE
E1.1: Suggestion to generalize certain use cases and to simplify the narrative to entry-level users

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#287]
Editor's comment:

> As a long-term but sporadic GitHub user myself, I agree with most of the points and cases presented in the paper.
>
> E1.1. I agree with Reviewer 1 that these could be streamlined somewhat into a smaller number of more generalizable cases. They also are a bit heavily weighted towards more experienced users. "Simple" operations like push, pull, and commit are rarely understandable to new users, who routinely forget to commit their actions. The GitHub Desktop app makes many of the operations and use of GitHub somewhat easier, and is a good entree into GitHub and Git for novices. More could be made of the desktop app.

The reviewer 1's  comment the editor is referring to is R1.1, which can be found in issue #277.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by kaitlyngaynor** [comment]
Also seems like a key piece of this comment is to mention GitHub Desktop somewhere. I don't use it myself, but maybe somebody who does can make a recommendation about where to integrate it?

**Comment by Aariq** [comment]
If we haven't mentioned it already (honestly can't remember), we might also mention that RStudio has a GUI for all the most commonly used GitHub commands.

**Comment by emmajhudgins** [comment]
I can take on the github desktop/rstudio GIU discussion. 

re: the second part, Ideas on which use cases to discard/modify?

**Comment by Aariq** [comment]
We can discuss which use cases to discard/modify here maybe: https://github.com/SORTEE-Github-Hackathon/manuscript/discussions/292

**Comment by robcrystalornelas** [comment]
Do we agree that this comment is addressed in #292 or should more be done here? I think @Aariq has done a nice job of calling out additional ways that we can use core Git features for collaboration on code in #292.

Also want to note that we do mention **GitHub desktop and R studio's GUI** for interacting with Git in Box 1 and also (GitHub Desktop) in our introduction:

> Although the understanding of basic concepts of Git (such as commit, push, pull, checkout; see [Box 1](#definitions)) is necessary, the GitHub web-based platform and its integrated development environments (such as GitHub Desktop) allow users to perform most repository and data management operations without opening Git command-line sessions, making these functionalities available to users who are less familiar with software development.

Seems like we cover it well enough already.

**Comment by Aariq** [comment]
Yeah, I think we can say this has been addressed

**Comment by Aariq** [comment]
Still working on this

**Comment by pedrohbraga** [comment]
I will create a pull request with points addressing this issue by the end of the weekend. I expect that it should be enough to close this issue then.
