### ISSUE TITLE
E1.2: Emphasize the ability of making repositories private 

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#288]
Edtior's comment:

> E1.2. In my own experience, the "public" nature of repos is a major barrier to the use of GitHub for exactly the reason you suggest - EEB practioners remain very uncomfortable with sharing data pre-publication (and often even post-publication).  Some additional emphasis on the ability to make repos "private" should be included beyond the Boxes.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by kaitlyngaynor** [comment]
Seems like this could be easily done in the "Storing and sharing research compendia" section with a sentence, and maybe there could be another brief caveat in the "Open science discussion" that reminds readers that it doesn't _have_ to be open if they don't want it to be.

**Comment by pedrohbraga** [comment]
This issue has been addressed in #293. Thank you, @katherinehebert for the PR and @kaitlyngaynor for the input! 

I am closing this issue, which can always be reopened if we need to.
