### ISSUE TITLE
IMPORTANT: Co-author approval of the revised manuscript, response letter, and authorship order

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#309]
# Co-author checklist for the submission of the revised version of our manuscript

Hi all! We are about to submit the revised version of our manuscript to Methods in Ecology and Evolution.

Here is a little checklist below for you to complete:

1. Read through the revised manuscript, which is available [at this link](https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html);
2. Read through the response letter, which is available [at this link](https://sortee-github-hackathon.github.io/manuscript/editorial-communication/response-to-the-reviewers.html);
3. Confirm whether you approve the adjustments to authorship order to account for effort in the revisions (see below);
4. If applicable, update your information in the [metadata](https://github.com/SORTEE-Github-Hackathon/manuscript/blob/main/content/metadata.yaml) via a pull request;
5. Check the box below if you have gone through this checklist and approve the submission of the modifications and the submission of the revised version of our manuscript.

### Adjusted authorship order 

|             Proposed authorship order:                                         |             Current authorship order:                                      |
| --------------------------------------- | ---------------------------------------- |
| Pedro Henrique Pereira Braga (co-first) | Robert Crystal-Ornelas (first)           |
| Katherine Hébert (co-second)            | Brandon P.M. Edwards (co-second)         |
| Emma J. Hudgins (co-second)             | Katherine Hébert (co-second)             |
| Eric R. Scott (co-second)               | Emma J. Hudgins (co-second)              |
| Brandon P.M. Edwards (co-second)        | Luna L. Sánchez Reyes (co-second)        |
| Luna L. Sánchez Reyes (co-second)       | Eric R. Scott                            |
| Matthew J. Grainger                     | Matthew J. Grainger                      |
| Vivienne Foroughirad                    | Vivienne Foroughirad                     |
| Friederike Hillemann                    |               Allison D. Binley            |
| Allison D. Binley                       |        Cole B. Brookson            |
| Cole B. Brookson                        |     Kaitlyn M. Gaynor          |
| Kaitlyn M. Gaynor                       |     Saeed Shafiei Sabet                                 |
| Saeed Shafiei Sabet                     |        Ali Güncan                 |
| Ali Güncan                              |       Friederike Hillemann                 |
| Helen Weierbach                         | Helen Weierbach                          |
| Dylan G. E. Gomes                       | Dylan G. E. Gomes                        |
| Robert Crystal-Ornelas (co-first)       | Pedro Henrique Pereira Braga (co-second) |

# Co-author approval (**Deadline: Tuesday, March, 7th**)

- [x] Ali Güncan (@Aguncan)
- [x] Allison D. Binley (@adbinley)
- [x] Brandon P.M. Edwards (@BrandonEdwards)
- [x] Cole B. Brookson (@colebrookson)
- [x] Dylan G. E. Gomes (@dylangomes)
- [x] Emma J. Hudgins (@emmajhudgins)
- [x] Eric R. Scott (@Aariq)
- [x] Friederike Hillemann (@fhillemann)
- [ ] Helen Weierbach (@helenweierbach)
- [x] Kaitlyn M. Gaynor (@kaitlyngaynor)
- [x] Katherine Hébert (@katherinehebert)
- [x] Luna L. Sánchez Reyes (@LunaSare)
- [x] Matthew J. Grainger (@DrMattG)
- [x] Pedro Henrique Pereira Braga (@pedrohbraga)
- [x] Robert Crystal-Ornelas (@robcrystalornelas)
- [x] Saeed Shafiei Sabet (@shafieisabets)
- [x] Vivienne Foroughirad (@vjf2)

Please let me know if you find issues or would like to suggest modifications!

Thank you all for your help!!!

**Comment by emmajhudgins** [comment]
Thanks so much for all your work making this happen, @pedrohbraga ! I have a couple suggested changes in the response letter:

From R1.2 - 'for certain of their practices.' -> 'for some of their practices' or "for certain practices'

R1.4 - suggest 'so that it is presented as the second use case' or 'to the second use case'

woohoo!

**Comment by DrMattG** [comment]
Added some minor formatting issues in #311. Great work and thank you for pushing this forward!

**Comment by Aariq** [comment]
Made some minor edits (#316), and opened some issues (#312, #313, #314, #315) related to citation formatting.  I'm happy with it though so I give my approval.

**Comment by dylangomes** [comment]
1) I noticed that the manuscript cites our sharing data and code paper twice (once in the Proc B published version = Gomes et al. 2022a, and once in the pre-print version = Gomes et al. 2022b). I think we should make all of these refer to the published version of record (Gomes et al. 2022a -> Gomes et al. 2022), and remove reference to the pre-print. 

2) There are two cases where "e.g. " is missing the comma, for consistency. That is, in all other cases, we have "e.g., " or "i.e., ", but twice we have "e.g. " without the comma... very small point.

**Comment by Aariq** [comment]
> 1. I noticed that the manuscript cites our sharing data and code paper twice (once in the Proc B published version = Gomes et al. 2022a, and once in the pre-print version = Gomes et al. 2022b). I think we should make all of these refer to the published version of record (Gomes et al. 2022a -> Gomes et al. 2022), and remove reference to the pre-print.

I *think* I fixed this in #316 (but would be good to double-check)
