### ISSUE TITLE
DOI for sPlot paper not working

### ISSUE THREAD

**Issue by Aariq** [SORTEE-Github-Hackathon/manuscript#313]
Manubot gives the following error when building:

```
## ERROR
Error fetching metadata for doi:10.1111/geb.13346.
Invalid response from https://api.crossref.org/v1/works/10.1111%2Fgeb.13346/transform:

## WARNING
Error in get_doi_csl_item_default for 10.1111/geb.13346 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
## WARNING
Error parsing web_query output as JSON for https://doi.org/10.1111/geb.13346:
No items returned from any translator
## WARNING
Error in get_doi_csl_item_url for 10.1111/geb.13346 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
## WARNING
Error parsing search_query output as JSON for doi:10.1111/geb.13346:
No items returned from any translator
## WARNING
Error in get_doi_csl_item_zotero for 10.1111/geb.13346 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
## ERROR
Generating csl_item for 'doi:10.1111/geb.13346' failed due to a Exception:
all get_doi_csl_item methods failed for 10.1111/geb.13346
```

And the resulting in-text citation is not rendered:

> Then, an issue can be created to establish steps and responsibilities including data formatting, statistical analyses, figure generation, and issue resolution (e.g., see issues and discussions in the sPlotOpen manuscript repository, doi:10.1111/geb.13346?); Issues · Fmsabatini/sPlotOpen_Manuscript (n.d.)=is%3Aissue+is%3Aclosed]

**Comment by pedrohbraga** [comment]
Thank you! The link between the DOI and the journal webpage was not working. I reported it to CrossRef and they fixed the problem. This should be working in the next render of the manuscript.
