### ISSUE TITLE
Example Zenodo citations have bad metadata

### ISSUE THREAD

**Issue by Aariq** [SORTEE-Github-Hackathon/manuscript#314]
We provide example citations of Zenodo repositories, but they're not great examples since the metadata are not formatted well.  These are the citations generated by Manubot:

In-text:
>This strategy has been increasingly adopted in numerous studies in ecology and evolution (e.g., the Zenodo repositores for Hudgins (2022), EllenJCoombs (2020), and Lrharper1 (2018)).

In works cited:
>Hudgins, E. (2022). emmajhudgins/UStreedamage: publication release (accepted) [Computer
software]. Zenodo. https://doi.org/10.5281/zenodo.6097109

>Lrharper1. (2018). Hulluni-Bioinformatics/Harper_Et_Al_2018: Github Repository Deposited With Harper Et Al. (2018) In Ecology And Evolution. Zenodo. https://doi.org/10.5281/zenodo.1188710

>EllenJCoombs. (2020). EllenJCoombs/Asymmetry-evolution-cetaceans-for-publication-v.1.0.0 (Version v.1.0.0) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.3893943

The one for Hudgins 2022 looks fine (but @emmajhudgins may want to review and potentially revise the title).  The other two are pretty bad.  Either make custom citations, get the owners of those archives to fix the metadata, or choose different examples.

**Comment by pedrohbraga** [comment]
I agree with this, @Aariq! I will replace the citations for the other ones with clearer ones (from myself), and I will manually change the title for @emmajhudgins's one to "Data and code for 'Hotspots of pest‐induced US urban tree death, 2020–2050', published in Journal of Applied Ecology".

**Comment by pedrohbraga** [comment]
Fixed in https://github.com/SORTEE-Github-Hackathon/manuscript/commit/2ba66415ee4d5e69b7890e54bec942747e76e441! Thank you, @Aariq !
