### ISSUE TITLE
Formatting tables

### ISSUE THREAD

**Issue by dylangomes** [SORTEE-Github-Hackathon/manuscript#69]
I am wondering how we want to make tables for this manuscript written in GitHub. There are probably many options. I typically make tables in Word or with R markdown (e.g. kable, etc.). The HackMD table looks nice, but will that work the same way in our document? Do we want to standardize how we do this?

Thoughts?

**Comment by Aariq** [comment]
So the way I did it in #43 was with R markdown knit to .md, but then to update it, the .Rmd file needs to be edited, not the .md, and then re-knit.

**Comment by pedrohbraga** [comment]
I will look into this later this week. There should be a way to make this work.

If there is no way, a potential solution would be to use the [`gt`](https://gt.rstudio.com/) R package, which allows the creation of nice, publication-quality tables (_e.g._ this [one](https://www.liamdbailey.com/post/making-beautiful-tables-with-gt/)). This package allows a lot of freedom in the customization of the table (e.g. size, paragraph, font, the inclusion of figures).

A reproducible workflow could be:
1. Create everything needed to reproduce the table within an `.Rmd` file;
2. Create a Github Action to run and output the table every time it is changed; and,
3. If Manubot allows for a lot of flexibility with the usage of tables, bring the output code of the `.Rmd` directly to the manuscript `.md` content files within `/content`; or,
4. If Manubot does not allow for a table that looks like as we would like it to be, then the `.Rmd` and the Github Action should export a high-resolution or vectorized image with a fixed name, and then add this table to the manuscript using `![Caption for the example figure.](url_or_path_to_figure){#fig:example-id}`.

**Comment by Aariq** [comment]
Can `gt` output as Word or latex though?  We probably can't submit a .md or .html doc to most journals.

**Comment by pedrohbraga** [comment]
`gt` outputs tables as HTML, PDF, PNG, LaTeX, and RTF files, as well as Shiny.

![image](https://user-images.githubusercontent.com/8599229/151863755-85f409cb-f9e1-48d9-a378-04a36b15eade.png)

Manubot uses Pandoc to convert manuscripts from Markdown to HTML, LaTeX, PDF, and DOCX outputs. So far, I believe that we have no major limitations related to the output format here.

A potential integration could see how we can export the manuscript towards a format accepted by `rticles` as well, which can then go directly in the format that journals require.

**Comment by Aariq** [comment]
I'm going to take a crack at a .R script for us to put all the (R) figure and table generation code in.  I think then I can just add a line to the manubot github action to run that script before building the manuscript.
